### ISSUE TITLE
OpenGL Support On Raspberry Pi And Linux ARM Devices

### ISSUE THREAD

**Issue by jessefreeman** [PixelVision8/Bounties#3]
**Bounty Information:**
I'm currently looking for help to get Pixel Vision 8 running on ARM device like the Raspberry Pi with OpenGL support. While you can run the Linux version of PV8 on a Pi, it's defaulting to software render, making it too slow to use. The solution fo this bounty is to get PV8 running at over 30-40 frames a second and ideally 60 FPS on the latest Pi device.

**Work Needed:**
I have been unable to find enough documentation on how to properly get MonoGame (which PV8 is built on top of) to work on Raspberry Pi and other Linux ARM-based SOCs. Pixel Vision 8's [core C# runner](https://github.com/PixelVision8/PixelVisionRunner) will need to either A) be recompiled exclusively for Linux ARM with OpenGL support or B) recompile SDL2 (which MonoGame uses under the hood) to run in OpenGL mode in a way that MonoGame can use.

**Prerequisites:**
Knowledge of how MonoGame renders on Linux and how to get hardware acceleration (OpenGL) to work.

**What help can I provide?**
I can provide my build scrips to help automate the process of generating an ARM build once a solution has been submitted.

**Budget/Timeline:**
I expect this to take about four days. One day spent on reading/research and two days spent on implementation/testing. Finally, one day to stress test and verify that it runs correctly with hardware acceleration. I currently have $200 USD allocated for this project.

**Claim This Bounty:**
If you want to take on this bounty, leave a comment and I'll add you to the repo and assign it to you so others know it's being worked on.

**Comment by Torbuntu** [comment]
I'm very interested in getting this to work. I don't know if I will get it within 4 days, but I am working on it already.

**Comment by jessefreeman** [comment]
I'll assign this to you after you accept the invite to join the project. Take the time you need. I think the issues aren't actually with OpenGL based on some other feedback I got ([https://twitter.com/procfxgen/status/1247133178533416960](https://twitter.com/procfxgen/status/1247133178533416960)) but maybe there is something I'm missing. It might just be the way PV8 renders that is slowing it down on ARM devices. Keep me posted!

**Comment by jessefreeman** [comment]
I've completed the foundation for this in the new 0.9.8 build. I rewrote the shader, ported the engine over to NetCore 3.1, and have to optimize the renderer to make PV8 run better on a PI.
